## Packages needed to generate and analyse o2geosocial runs

library(data.table)
library(o2geosocial)
library(geosphere)
library(dplyr)
library(Rcpp)
library(grid)
library(ggplot2)
library(gridBase)
library(gridExtra)
library(expm)
library(RColorBrewer)
library(Hmisc)
library(socialmixr)
